#1 what is the total revenue generated by male vs female suto.?
SELECT gender,sum(purchase_amount) as revenue
FROM customer_behavior.customer
group by gender;

#2 which customer used discount but still spent more than average purchase amount

SELECT customer_id,purchase_amount
FROM customer_behavior.customer
WHERE discount_applied= 'yes' and purchase_amount >= (SELECT AVG(purchase_amount) FROM customer_behavior.customer);


# find the top performer?

SELECT item_purchase, avg(review_rating) as average_rating
from customer_behavior.customer
group by item_purchase
LIMIT 5;

#compair the avg purchase amount b/w  standard and express shipping?

select shipping_type, round(avg(purchase_amount),2)
from customer_behavior.customer
group by shipping_type;

# do suscriber cust spend more? compare avg spend and total spend b/w suscriber. and non-sus.?alter

select subscription_status,
count(customer_id) as total_cust,
round(avg(purchase_amount),2) as avg_spend,
round(sum(purchase_amount),2) as total_spend
from customer_behavior.customer
group by subscription_status;

# which 5 item have highest %  of purchase	with discount_applied?

SELECT item_purchased,
ROUND((SUM(CASE WHEN discount_applied = 'yes' THEN 1 ELSE 0 END) / COUNT(*)) * 100,2) AS discount_rate
FROM customer_behavior.customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

#segment cust into new, returning, and loyal based on their total number of previous purchase ans show the count of each segment!

with customer_type as (select customer_id, previous_purchases,
case 
when previous_purchases = 1 then 'new'
when previous_purchases between 2 and 10 then 'returning'
else 'loyal'
end as customer_segment from customer_behavior.customer)

select customer_segment,count(*) as 'no. of customer'
from customer_type
group by customer_segment;

# what are the 3 top most purchased in each category? --super important

with item_counts as (
select category,item_purchased,
count(customer_id) as total_order,
row_number() over (partition by category order by  count(customer_id) desc) as item_rank
from customer_behavior.customer
group by category,item_purchased)

select item_rank,category, item_purchased, total_order
from item_counts
where item_rank<=3;

# Are cust. who are repeat buyers(more than 5 repeat purchase) also likely to subscribe?

select subscription_status,
count(customer_id) as repeat_buyers
from customer_behavior.customer
where previous_purchases >5
group by subscription_status;

# what is the revenue contribution of each group?

select age_group,
sum(purchase_amount) as total_revenue
from customer_behavior.customer
group by age_group
order by total_revenue desc;







